#
#Wed Jun 10 23:03:10 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--start-maximized, --disable-notifications, --disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
