#
#Wed Jun 10 22:45:21 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--start-maximized, --disable-notifications, --disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
